### PR TITLE
remove 3.6, add 3.9

### PR DESCRIPTION
**Pull request by satra**

### CODE REVIEW

**Comment by satra** [comment]
looks like 3.9 install is not clean for dandi. (@jwodder , @yarikoptic). this might show up in several places since many people install py39 now as default.

**Comment by jwodder** [comment]
@satra Yeah, you need to install libhdf5-dev and numpy<1.19.4 first before installing dandi on 3.9 (cf. [dandi-cli's test workflow](https://github.com/dandi/dandi-cli/blob/master/.github/workflows/test.yml)).

**Comment by satra** [comment]
shouldn't that be in the setup.cfg?

**Comment by jwodder** [comment]
@satra It can't.  Installing libhdf5 is outside the scope of setuptools, and installing numpy needs to be done before installing h5py.  There is no clean way to do that with the Python packaging system.  Note that this should cease to be a problem once hdmf updates to support h5py 3.0, whenever that is.

**Comment by satra** [comment]
in that case perhaps we should limit dandi cli to be < 3.9. as this is going to be an issue for many users since pynwb is not just a test dependency.

**Comment by jwodder** [comment]
@satra I'd prefer it if we instead just documented the necessary steps for installing under Python 3.9 rather than blocking off installation completely.

**Comment by satra** [comment]
many of our users would not know how to do this. we were troubleshooting various installation steps yesterday, so i would like to provide the simplest path out. libhdf-dev is not an easy install for people. we could document that if using python 3.9 please install using conda, but even the conda install doesn't support 3.9 at the moment. so i would prefer restricting it at this point.

**Pull request merged**
