### PR TITLE
RF: do not cast dataset id to an int and back  to %06d

### PR DESCRIPTION
**Pull request by yarikoptic**
I think there is no need to be "that smart" and use identifier as given. That could avoid discrepancies, such as the one I managed to inflict in https://github.com/dandi/dandi-cli/issues/302 . Thanks to @jwodder for pin pointing this in https://github.com/dandi/dandi-cli/issues/302#issuecomment-778445808

### CODE REVIEW

**Comment by satra** [comment]
there seems to be a return code difference in the tests likely from the girder server. also we should not rely i think on a response from the server for the id check. we should be checking through regex before sending it onto the server.

**Comment by yarikoptic** [comment]
@jwodder , please finalize this PR

**Comment by jwodder** [comment]
@yarikoptic I don't have permission to push to this repository.

**Comment by jwodder** [comment]
@yarikoptic @satra I've fixed the tests and added a check of Dandiset IDs against a regex.

**Comment by jwodder** [comment]
@satra Please merge this PR.  It contains test fixes that are needed before I can make further changes to the code.

**Pull request merged**
