### PR TITLE
Add env var for pointing Dandi integration tests to containerized redirector

### LINKED ISSUE #42: make dandi-cli tests use the PR version of the redirector
as green #40 and red #41 shows - ATM we test against deployed redirector.

### PR DESCRIPTION
**Pull request by jwodder**
Closes #42.

https://github.com/dandi/dandi-cli/pull/581 must be merged & released in order for this to work.

### CODE REVIEW

**Comment by yarikoptic** [comment]
cli PR was merged (and IIRC released), so I guess this PR just needs a "refresh", right @jwodder ?

**Comment by jwodder** [comment]
@yarikoptic I believe that this change is needed for the PR to succeed: https://github.com/dandi/dandi-cli/pull/612

**Comment by jwodder** [comment]
@yarikoptic The tests pass now.

**Comment by yarikoptic** [comment]
@satra -- should we just merge this one? ;-)

**Pull request merged**
